
# Site settings

title: CubPack.org

email: hello@cubpack.org
description: >- 
  Free subdomains for cub packs. Get yourpack.cubpack.org for free
url: "https://www.cubpack.org" 

# Theme Settings
comments: false
favicon: /favicon.ico

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - github-pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
